import { useState, useEffect, useContext } from "react";
import AuthContext from "../context/AuthContext";

const AdminDashboard = () => {
    const { authTokens } = useContext(AuthContext);
    const [organizers, setOrganizers] = useState([]);
    const [loading, setLoading] = useState(true);

    // New Organizer Form State
    const [formData, setFormData] = useState({
        organizerName: "", email: "", category: "", description: "", contactEmail: ""
    });
    const [createdCredentials, setCreatedCredentials] = useState(null);
    const [error, setError] = useState("");

    // Fetch existing organizers using the admin endpoint (includes email)
    const fetchOrganizers = async () => {
        try {
            const response = await fetch(`${process.env.REACT_APP_API_URL}/api/admin/organizers`, {
                headers: { "x-auth-token": authTokens.token }
            });
            const data = await response.json();
            if (response.ok) setOrganizers(data);
        } catch (err) {
            console.error("Failed to fetch organizers");
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchOrganizers();
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [authTokens]);

    const handleInputChange = (e) => {
        setFormData({ ...formData, [e.target.name]: e.target.value });
    };

    // Auto-generate a random 10-character password
    const generatePassword = () => {
        return Math.random().toString(36).slice(-10) + Math.random().toString(36).slice(-4).toUpperCase();
    };

    const handleCreateOrganizer = async (e) => {
        e.preventDefault();
        setError("");
        setCreatedCredentials(null);

        const autoGeneratedPassword = generatePassword();

        try {
            const response = await fetch(`${process.env.REACT_APP_API_URL}/api/admin/create-organizer`, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "x-auth-token": authTokens.token
                },
                body: JSON.stringify({
                    ...formData,
                    password: autoGeneratedPassword // Send the generated password to backend
                })
            });

            const data = await response.json();

            if (response.ok) {
                // Show credentials to Admin so they can copy/share them
                setCreatedCredentials({ email: formData.email, password: autoGeneratedPassword });
                setFormData({ organizerName: "", email: "", category: "", description: "", contactEmail: "" }); // Clear form
                fetchOrganizers(); // Refresh list
            } else {
                setError(data.msg || "Creation failed");
            }
        } catch (err) {
            setError("Server Error");
        }
    };

    const handleDelete = async (id, name) => {
        if (!window.confirm(`Are you sure you want to permanently delete ${name}?`)) return;

        try {
            const response = await fetch(`${process.env.REACT_APP_API_URL}/api/admin/organizers/${id}`, {
                method: "DELETE",
                headers: { "x-auth-token": authTokens.token }
            });

            if (response.ok) {
                fetchOrganizers(); // Refresh list
            } else {
                alert("Failed to delete organizer");
            }
        } catch (err) {
            alert("Server Error");
        }
    };

    const handleToggleStatus = async (id, currentStatus) => {
        const action = currentStatus === false ? "activate" : "disable";
        if (!window.confirm(`Are you sure you want to ${action} this account?`)) return;
        try {
            const response = await fetch(`${process.env.REACT_APP_API_URL}/api/admin/organizers/${id}/toggle-status`, {
                method: "PUT",
                headers: { "x-auth-token": authTokens.token }
            });
            if (response.ok) fetchOrganizers();
        } catch (err) {
            alert("Server Error");
        }
    };
    if (loading) return <div style={{ padding: "20px" }}>Loading Dashboard...</div>;

    return (
        <div style={{ padding: "20px", maxWidth: "1200px", margin: "auto" }}>
            <h1>Admin Dashboard</h1>

            <div style={{ display: "flex", gap: "30px", alignItems: "flex-start", flexWrap: "wrap" }}>

                {/* LEFT SIDE: Create Organizer Form */}
                <div style={{ flex: "1 1 400px", background: "#f9f9f9", padding: "20px", borderRadius: "8px", border: "1px solid #ddd" }}>
                    <h2>Provision New Organizer</h2>
                    <p style={{ color: "gray", fontSize: "0.9rem" }}>The system will auto-generate a secure password.</p>

                    {error && <p style={{ color: "red", fontWeight: "bold" }}>{error}</p>}

                    {createdCredentials && (
                        <div style={{ background: "#d4edda", padding: "15px", borderRadius: "5px", marginBottom: "15px", border: "1px solid #c3e6cb" }}>
                            <h4 style={{ margin: "0 0 10px 0", color: "#155724" }}>✅ Organizer Created!</h4>
                            <p style={{ margin: "5px 0" }}><strong>Login Email:</strong> {createdCredentials.email}</p>
                            <p style={{ margin: "5px 0" }}><strong>Password:</strong> <span style={{ fontFamily: "monospace", background: "white", padding: "2px 5px" }}>{createdCredentials.password}</span></p>
                            <small style={{ color: "#155724" }}>Please copy and securely share this password with the club. It will not be shown again.</small>
                        </div>
                    )}

                    <form onSubmit={handleCreateOrganizer} style={{ display: "flex", flexDirection: "column", gap: "15px" }}>
                        <input type="text" name="organizerName" placeholder="Club / Organizer Name" value={formData.organizerName} onChange={handleInputChange} required style={inputStyle} />
                        <input type="email" name="email" placeholder="Login Email (Unique)" value={formData.email} onChange={handleInputChange} required style={inputStyle} />
                        <input type="email" name="contactEmail" placeholder="Public Contact Email" value={formData.contactEmail} onChange={handleInputChange} required style={inputStyle} />
                        <input type="text" name="category" placeholder="Category (e.g., Technical, Cultural)" value={formData.category} onChange={handleInputChange} required style={inputStyle} />
                        <textarea name="description" placeholder="Short description of the club..." value={formData.description} onChange={handleInputChange} required style={{ ...inputStyle, height: "80px" }} />

                        <button type="submit" style={{ padding: "12px", background: "#007bff", color: "white", border: "none", borderRadius: "4px", cursor: "pointer", fontWeight: "bold" }}>
                            Create Organizer Account
                        </button>
                    </form>
                </div>

                {/* RIGHT SIDE: Manage Existing Organizers */}
                <div style={{ flex: "2 1 500px", background: "white", padding: "20px", borderRadius: "8px", border: "1px solid #ddd" }}>
                    <h2>Manage Organizers ({organizers.length})</h2>

                    <div style={{ overflowX: "auto" }}>
                        <table style={{ width: "100%", borderCollapse: "collapse", textAlign: "left" }}>
                            <thead>
                                <tr style={{ background: "#f8f9fa", borderBottom: "2px solid #ccc" }}>
                                    <th style={thStyle}>Name</th>
                                    <th style={thStyle}>Category</th>
                                    <th style={thStyle}>Login Email</th>
                                    <th style={thStyle}>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {organizers.map(org => (
                                    <tr key={org._id} style={{ borderBottom: "1px solid #eee" }}>
                                        <td style={tdStyle}><strong>{org.organizerName}</strong></td>
                                        <td style={tdStyle}>{org.organizerCategory}</td>
                                        <td style={tdStyle}>{org.email}</td>
                                        <td style={tdStyle}>
                                            {org.isActive === false && <span style={{ color: 'red', marginRight: '10px' }}>(Disabled)</span>}
                                            <button
                                                onClick={() => handleToggleStatus(org._id, org.isActive)}
                                                style={{ padding: '5px 10px', background: '#ffc107', color: 'black', border: 'none', borderRadius: '3px', cursor: 'pointer', marginRight: '10px' }}
                                            >
                                                {org.isActive === false ? 'Activate' : 'Disable'}
                                            </button>
                                            <button
                                                onClick={() => handleDelete(org._id, org.organizerName)}
                                                style={{ padding: "5px 10px", background: "#dc3545", color: "white", border: "none", borderRadius: "3px", cursor: "pointer" }}
                                            >
                                                Remove
                                            </button>
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    );
};

const inputStyle = { width: "100%", padding: "10px", border: "1px solid #ccc", borderRadius: "4px", boxSizing: "border-box" };
const thStyle = { padding: "12px", color: "#333" };
const tdStyle = { padding: "12px" };

export default AdminDashboard;